---
# tasks file for ansible-macdock

- name: '[dock] Get info about items to be removed'
  shell: "/usr/local/bin/dockutil --find '{{ item }}'"
  register: macdock_items_remove
  with_items: "{{ macdock_remove_items }}"
  changed_when: false
  failed_when: false
  check_mode: no
  when: not macdock_items_remove_all|bool

- name: '[dock] Remove all dock items'
  shell: "/usr/local/bin/dockutil --remove all --no-restart"
  register: macdock_removed_items_task
  when: macdock_items_remove_all|bool

- name: '[dock] Remove all unwanted dock items'
  shell: "/usr/local/bin/dockutil --remove '{{ item.item }}' --no-restart"
  with_items: "{{ macdock_items_remove.results }}"
  loop_control:
    label: "{{item.item}}"
  when:
  - not macdock_items_remove_all|bool
  - (item.item ~ " was found in persistent-apps") in item.stdout
  notify: Restart Dock

- name: '[dock] Get information on configured setup'
  shell: "/usr/local/bin/dockutil --find '{{ item.name }}'"
  register: macdock_dockutil
  with_items: "{{ macdock_add_items }}"
  changed_when: false
  failed_when: false
  check_mode: no

- name: '[dock] Add items to dock'
  shell: "/usr/local/bin/dockutil --add '{{ item.item.path }}' --position {{ item.item.pos }} --no-restart"
  with_items: "{{ macdock_dockutil.results }}"
  loop_control:
    label: "{{item.item}}"
  when: (item.item.name ~ " was not found in") in item.stdout
  notify: Restart Dock

- name: '[dock] Get information on current setup'
  shell: "/usr/local/bin/dockutil --find '{{ item.name }}'"
  register: macdock_dockutil_current
  with_items: "{{ macdock_add_items }}"
  changed_when: false
  failed_when: false
  check_mode: no

- name: '[dock] Moving items'
  shell: "/usr/local/bin/dockutil --move '{{ item.item.name }}' --position {{ item.item.pos }} --no-restart"
  with_items: "{{ macdock_dockutil_current.results }}"
  loop_control:
    label: "{{item.item}}"
  when:
  - (item.item.name ~ " was found in persistent-apps at slot " ~ item.item.pos ~ " in") not in item.stdout
  - (item.item.name ~ " was not found") not in item.stdout
  notify: Restart Dock
...
